numJo1 = float(input())
numJo2 = float(input())
numJo3 = float(input())
numMa1 = float(input())
numMa2 = float(input())
numMa3 = float(input())
fEduardo = input()
fMonica = input()
fDataEdu = int(input())
fDataMon = int(input())
vHotel = float(input())
vAviao = float(input())

respo1 = (numJo1 >= 7) and (numJo2 >= 7) and (numJo3 >= 7)
respo2 = (numMa1 >= 7) and (numMa2 >= 7) and (numMa3 >= 7)
respo3 = (fEduardo == "Sim") and (fMonica == "Sim") 
respo4 = (fDataEdu <= 15) and (fDataMon <= 15)
respo5 = (vHotel + vAviao <= 10000)
respo6 = (respo1 == True) and (respo2 == True) and (respo3 == True) and (respo4 == True) and (respo5 == True)

print("Joao aprovado em todas as disciplinas? {}".format(respo1))
print("Maria aprovada em todas as disciplinas? {}".format(respo2))
print("Eduardo e Monica de ferias de dezembro? {}".format(respo3))
print("Pagamento de Eduardo ou Monica liberado a tempo? {}".format(respo4))
print("Valor total menor ou igual a R$10.000,00? {}".format(respo5))
print("Irao viajar? {}".format(respo6))
